name: Linux GCC/Clang Qt5.15

on:
  pull_request:
  push:
    branches:
      - main
      - gh-actions

jobs:

  build:
    name: cmake build / ctest

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: vcpkg upgrade
      run: |
        pwd
        cd "$VCPKG_INSTALLATION_ROOT"
        echo $VCPKG_INSTALLATION_ROOT
        pwd
        git pull
        vcpkg update
